from results import ResultsAll, ResultsSingle
from wizard_general import FlashWizardGeneral
from wizard_select import FlashWizardSelectShot
from wizard_shot import FlashWizardShotPrototype
from wizard_progress import FlashWizard